import { createSupabaseRouteClient } from "@/lib/supabase/server";
import { orderCreateSchema } from "@/lib/validation/order";
import { apiError, apiOk, apiUnauthorized, apiValidationError } from "@/lib/api-response";

export async function GET(request: Request) {
  const supabase = await createSupabaseRouteClient(request);
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return apiUnauthorized();

  const { searchParams } = new URL(request.url);
  const stage = searchParams.get("stage");

  let query = supabase.from("orders").select("*").order("due_date", { ascending: true });
  if (stage) query = query.eq("stage", stage);

  const { data, error } = await query;
  if (error) return apiError(500, "query_failed", "Could not load orders");
  return apiOk(data);
}

// order_code and tracking_token are generated by the database (trigger + column
// default) — never accepted from the client.
export async function POST(request: Request) {
  const supabase = await createSupabaseRouteClient(request);
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return apiUnauthorized();

  const body = await request.json().catch(() => null);
  if (!body) return apiError(400, "invalid_body", "Request body must be JSON");

  const parsed = orderCreateSchema.safeParse(body);
  if (!parsed.success) return apiValidationError(parsed.error);

  const { data: boutique } = await supabase
    .from("boutiques")
    .select("id")
    .eq("owner_user_id", user.id)
    .maybeSingle();
  if (!boutique) return apiError(404, "no_boutique", "No boutique is registered for this account");

  const {
    customerId,
    garmentType,
    garmentTypeOther,
    dueDate,
    totalAmount,
    advanceAmount,
    tailorName,
    clothDescription,
    styleNotes,
    measurements,
  } = parsed.data;

  const { data, error } = await supabase
    .from("orders")
    .insert({
      boutique_id: boutique.id,
      customer_id: customerId,
      garment_type: garmentType,
      garment_type_other: garmentType === "Other" ? garmentTypeOther || null : null,
      due_date: dueDate,
      total_amount: totalAmount,
      advance_amount: advanceAmount,
      tailor_name: tailorName || null,
      cloth_description: clothDescription || null,
      style_notes: styleNotes || null,
      ...measurements,
    })
    .select()
    .single();

  if (error) {
    // status='on_hold' or 'disabled' surfaces here as an RLS insert denial.
    return apiError(403, "insert_failed", "Could not create the order (check boutique status)");
  }

  return apiOk(data, 201);
}
